name: Auto Release on File Changes

on:
  push:
    paths:
      - 'index.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Get version from package.json
      id: get_version
      run: |
        echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_ENV

    - name: Zip changed files
      run: |
        zip -r update-v${{ steps.get_version.outputs.VERSION }}.zip index.js package.json package-lock.json

    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          update-v${{ steps.get_version.outputs.VERSION }}.zip
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        name: Update v${{ steps.get_version.outputs.VERSION }}
        body: |
          Changes in:
          - index.js
          - package.json
          - package-lock.json
        token: ${{ secrets.GITHUB_TOKEN }}
    
    permissions:
      contents: write
      discussions: write